### ISSUE TITLE
单独编译运行ParticleEditor2D

### ISSUE THREAD

**Issue by justinlm** [aster2013/ParticleEditor2D#1]
你好，如题问下可以单独编译运行ParticleEditor2D这个工具吗。因为看见里面没有qt的.pro文件，而且看说明说要放在引擎Urho3D下的source下。
如果不能单独编译的话，能麻烦支持下么，或者教一下，谢谢。

**Comment by aster2013** [comment]
你好，当时这个直接用的Urho3D的cmake来创建工程的，没有单独配置Qt的.pro文件，如果你要单独编译需要自己搞一下。谢谢。

**Comment by justinlm** [comment]
好的，谢谢
